version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6380:6379'

  worker_app:
    build: './worker_app'
    volumes:
      - ./files:/worker_app/app_module/files
    depends_on:
      - db
      - redis

  gateway_app:
    build: './gateway_app'
    ports:
      - '8001:8001'
    volumes:
      - ./files:/gateway_app/app/files
    depends_on:
      - db
      - redis
      - worker_app
